# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: StenaldernsSamfallighet/hemsida
  branch: cms-test
  base_url: https://sveltia-cms-auth.weathered-scene-e537.workers.dev

media_folder: /static/uploads
public_folder: /uploads

collections:
  - name: nyheter
    label: Nyheter
    folder: /content/nyheter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }