name: "Nytt inlägg"

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      text:
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Checkout main
      run: git checkout main
    - name: Run check of pwd
      run: pwd
    - name: Run check of what's in pwd
      run: ls
    - name: Create new post
      run: bash ./.github/workflows/new.sh ${{ github.event.inputs.title }} ${{ github.event.inputs.text }}
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Nytt Inlägg
