name: "Nytt inlägg"

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      text:
        required: true
jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v1
    - name: Run check of pwd
      run: pwd
    - name: Run check of what's in pwd
      run: ls
    - name: Run a one-line script
      run: echo """
---
title: ${{ github.event.inputs.title }}
date: $(date --iso-8601='seconds')
---
${{ github.event.inputs.text }}
""" > content/nyheter/${{ github.event.inputs.title }}
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "${{ github.event.inputs.title }}"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
